### Loading the necessary libraries

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

### Loading the dataset into a pandas dataframe

In [2]:
df_population_growth = pd.read_csv("Population growth.csv")
df_power_consumption = pd.read_csv("Electric power consumption.csv")

In [3]:
df_population_growth.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Population growth (annual %),SP.POP.GROW,NaN,2.236462,1.432843,0.823502,0.580334,0.573498,...,0.377979,0.503385,0.583290,0.590508,0.541048,0.502860,0.471874,0.459266,0.437415,0.428017
1,Africa Eastern and Southern,AFE,Population growth (annual %),SP.POP.GROW,NaN,2.539822,2.575182,2.606839,2.633213,2.656488,...,2.756619,2.763426,2.761496,2.750400,2.732598,2.712218,2.690902,2.665620,2.636666,2.605427
2,Afghanistan,AFG,Population growth (annual %),SP.POP.GROW,NaN,1.898499,1.965805,2.029830,2.090208,2.147639,...,3.143106,3.407600,3.494592,3.355602,3.077054,2.778035,2.547833,2.384309,2.313073,2.303812
3,Africa Western and Central,AFW,Population growth (annual %),SP.POP.GROW,2.034308,2.085972,2.133725,2.173361,2.202845,2.226134,...,2.775171,2.763803,2.753564,2.745542,2.738332,2.730332,2.719330,2.704168,2.684152,2.660902
4,Angola,AGO,Population growth (annual %),SP.POP.GROW,NaN,1.392891,1.383296,1.256405,0.973970,0.618450,...,3.634150,3.597755,3.551997,3.497447,3.438869,3.378269,3.322158,3.276145,3.242914,3.218530

In [4]:
df_power_consumption.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,740.741606,703.908401,698.369914,686.728057,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,175.112546,185.515814,181.128875,186.199010,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Electric power consumption (kWh per capita),EG.USE.ELEC.KH.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,207.013351,219.253483,280.214482,312.228894,NaN,NaN,NaN,NaN,NaN,NaN